### ISSUE TITLE
Is type `SerializerCompiler` correct ?

### ISSUE THREAD

**Issue by remidewitte** [fastify/fast-json-stringify-compiler#47]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,

From my research, I have the feeling that the declared `SerializerCompiler` might be wrong.

In fastify, compiler is eventually called this way : 
```js
serializerCompiler({
    schema,
    method,
    url,
    httpStatus,
    contentType
  })
```

In fast-json-stringify-compiler; with jfsOpts being already bounded,
```js
function responseSchemaCompiler (fjsOpts, { schema /* method, url, httpStatus */ }) { ... }
```

My conclusion is that `SerializerCompiler` should be:
```ts
export type SerializerCompiler = (routeDef : RouteDefinition) => Serializer;
```

What do you think ?

**Comment by climba03003** [comment]
Then the question is how https://github.com/fastify/fastify/blob/6564ba9b7d8ec7c236cc16f4bf3cdb3cabff69f0/lib/schema-controller.js#L159 be even possible?

**Comment by remidewitte** [comment]
> Then the question is how https://github.com/fastify/fastify/blob/6564ba9b7d8ec7c236cc16f4bf3cdb3cabff69f0/lib/schema-controller.js#L159 be even possible?

Not sure but I would say : https://github.com/fastify/fast-json-stringify-compiler/blob/main/standalone.js#L25

**Comment by climba03003** [comment]
But it is not imported as standalone and the two version expect different arguments.

cc @Eomm

**Comment by Eomm** [comment]
Let's follow the happy path:

1. fastify starts and the user has set 1 response schema at least
2. fastify creates the default schema controller https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/fastify.js#L214
3. while creating the schema controller, the default serializer factory is instantiated https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/lib/schema-controller.js#L27C40-L27C58
4. Here is the factory function: https://github.com/fastify/fast-json-stringify-compiler/blob/6e8d53ac23618cd06e2c3caf806778098d810b8a/index.js#L6
5. Now the server is starting and fastify processes the route with the json schema
6. Since we don't have a FJS instance, the route asks to the schema controller to build a serializer https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/lib/route.js#L420
7. The serializer is built using the factory at step 3 (interface at step 4) https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/lib/schema-controller.js#L159
8. Finally we have the `compile` function generated by FJS and it is used to build the serializer-function https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/lib/validation.js#L35

> My conclusion is that SerializerCompiler should be:

It makes sense, but porting a real test case here will solve any doubt: https://github.com/fastify/fastify/blob/main/test/schema-serialization.test.js

**Comment by remidewitte** [comment]
Thanks for the fast feedback.

Indeed, in the happy path the compile function of type `SerializerCompiler` is called https://github.com/fastify/fastify/blob/main/lib/validation.js#L45 and https://github.com/fastify/fastify/blob/main/lib/validation.js#L45
In my opinion, it matches completely my initial suggestion.

About the real test case, as it is a js file and I am trying to solve a typing issue, I don't really understand what I could add to the PR, can you explain a bit more ?

Maybe less important `httpStatus` might be null : https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/lib/reply.js#L382
